# Generated by Django 6.0.6 on 2026-07-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0011_rename_contracto_to_contrato_and_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Ex: Dell, Lenovo, HP, Samsung', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Ex: Latitude 5420, ThinkPad E14', max_length=150, verbose_name='Modelo')),
                ('categoria', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('REDE', 'Equipamento de Rede'), ('IMPRESSORA', 'Impressora'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, help_text='Processador, RAM, armazenamento e outros detalhes relevantes.', null=True, verbose_name='Descrição / Especificações')),
            ],
            options={
                'verbose_name': 'Modelo de Equipamento',
                'verbose_name_plural': 'Modelos de Equipamento',
                'ordering': ['marca', 'modelo'],
                'unique_together': {('marca', 'modelo')},
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(db_index=True, help_text='Identificador único gravado no hardware.', max_length=200, unique=True, verbose_name='Número de Série (S/N)')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Em Estoque'), ('ALOCADO', 'Alocado'), ('MANUTENCAO', 'Em Manutenção'), ('DESCARTE', 'Descarte')], db_index=True, default='ESTOQUE', max_length=20, verbose_name='Status Operacional')),
                ('unidade', models.CharField(blank=True, help_text='Ex: Matriz, Filial Manaus, Data Center', max_length=100, null=True, verbose_name='Unidade')),
                ('setor', models.CharField(blank=True, help_text='Ex: Financeiro, RH, TI, Diretoria', max_length=100, null=True, verbose_name='Setor')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('observacoes', models.TextField(blank=True, help_text='Histórico técnico, defeitos conhecidos ou notas relevantes.', null=True, verbose_name='Observações')),
                ('cliente_atual', models.ForeignKey(blank=True, help_text='Preenchido quando o ativo está alocado em um cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos_alocados', to='comercial.cliente', verbose_name='Cliente Atual')),
                ('modelo_equipamento', models.ForeignKey(help_text='Selecione o modelo no catálogo. Não é possível excluir modelos com ativos vinculados.', on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='inventario.modeloequipamento', verbose_name='Modelo do Equipamento')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
