# Generated by Django 6.0.6 on 2026-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloequipamento',
            name='categoria',
            field=models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('REDE', 'Ativo de Rede'), ('IMPRESSORA', 'Impressora'), ('TABLET', 'Tablet'), ('COLETOR', 'Coletor de Dados'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', max_length=50, verbose_name='Categoria'),
        ),
    ]
