# Generated by Django 6.0.6 on 2026-07-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_rename_contracto_to_contrato_and_managers'),
        ('inventario', '0002_add_tablet_coletor_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='status',
            field=models.CharField(choices=[('ESTOQUE', 'Em Estoque'), ('ALOCADO', 'Alocado'), ('TESTE', 'Em Teste (Trial)'), ('TRIAGEM', 'Em Triagem'), ('MANUTENCAO', 'Em Manutenção'), ('DESCARTE', 'Descarte')], db_index=True, default='ESTOQUE', max_length=20, verbose_name='Status Operacional'),
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALOCACAO', 'Alocação'), ('TESTE', 'Teste (Trial)'), ('DEVOLUCAO', 'Devolução'), ('TROCA', 'Troca (Swap)'), ('VISITA', 'Visita Técnica')], db_index=True, max_length=20, verbose_name='Tipo de Movimentação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('cautela_pdf', models.FileField(blank=True, null=True, upload_to='cautelas/', verbose_name='PDF da Cautela')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='comercial.cliente', verbose_name='Cliente')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_participadas', to='inventario.ativo', verbose_name='Ativo')),
                ('ativo_substituto', models.ForeignKey(blank=True, help_text='O ativo que substituiu o ativo principal (no caso de uma troca).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trocas_realizadas', to='inventario.ativo', verbose_name='Ativo Substituto (Apenas para Trocas)')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inventario.movimentacao')),
            ],
            options={
                'verbose_name': 'Item de Movimentação',
                'verbose_name_plural': 'Itens de Movimentação',
            },
        ),
    ]
