# Generated by Django 6.0.6 on 2026-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_ativo_status_movimentacao_movimentacaoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='controla_serial',
            field=models.BooleanField(default=True, help_text='Desmarque para acessórios/itens de lote (capas, fontes, berços) que não possuem S/N individual.', verbose_name='Controla Número de Série'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0, help_text='Apenas para itens com controla_serial=False. Controla a quantidade disponível.', verbose_name='Quantidade em Estoque'),
        ),
        migrations.AddField(
            model_name='movimentacaoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Para acessórios sem serial, indica quantas unidades foram movimentadas.', verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='numero_serie',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único gravado no hardware. Deixe vazio para itens sem serial.', max_length=200, null=True, unique=True, verbose_name='Número de Série (S/N)'),
        ),
    ]
