# Generated by Django 6.0.6 on 2026-06-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.CharField(max_length=50)),
                ('data_abertura', models.CharField(max_length=20)),
                ('nome_tecnico', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(max_length=150)),
                ('solicitante', models.CharField(max_length=100)),
                ('forma_atendimento', models.CharField(default='Presencial', max_length=50)),
                ('contato', models.CharField(max_length=50)),
                ('equipamento', models.CharField(max_length=100)),
                ('problema', models.TextField()),
                ('status', models.CharField(default='Aberto', max_length=50)),
                ('notificado_abertura', models.CharField(default='NÃO', max_length=10)),
                ('ultimo_comentario', models.TextField(blank=True, default='')),
                ('ultimo_status_notificado', models.CharField(default='Nenhum', max_length=50)),
            ],
        ),
    ]
