# Generated by Django 6.0.6 on 2026-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
