# Generated by Django 6.0.6 on 2026-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_chamado_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='data_abertura',
        ),
        migrations.AlterField(
            model_name='chamado',
            name='nome_tecnico',
            field=models.CharField(blank=True, default='Não atribuído', max_length=100, null=True),
        ),
    ]
