# Generated by Django 6.0.6 on 2026-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_chamado_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], default='Média', max_length=10),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Atendimento', 'Em Atendimento'), ('Aguardando Usuário', 'Aguardando Usuário'), ('Aguardando Terceiros', 'Aguardando Terceiros'), ('Resolvido', 'Resolvido'), ('Encerrado', 'Encerrado')], default='Aberto', max_length=50),
        ),
    ]
