# Generated by Django 6.0.6 on 2026-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_chamado_prioridade_alter_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='id_integracao',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
