# Generated by Django 6.0.6 on 2026-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_chamado_id_integracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='sla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
