# Generated by Django 6.0.6 on 2026-06-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('COMER', 'Comercial'), ('SUPOR', 'Suporte Técnico'), ('FINAN', 'Financeiro'), ('LIDER', 'Líder Geral'), ('DONO', 'Diretoria / Dono')], default='SUPOR', max_length=5, verbose_name='Cargo / Função'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor',
            field=models.CharField(choices=[('COMERCIAL', 'Comercial'), ('SUPORTE', 'Suporte Técnico / TI'), ('FINANCEIRO', 'Financeiro'), ('DIRETORIA', 'Diretoria / Gerência')], default='SUPORTE', max_length=20, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
