# Generated by Django 6.0.6 on 2026-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_colaborador_cargo_alter_colaborador_setor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('tipo', models.CharField(choices=[('urgente', '🔴 Urgente'), ('sucesso', '🟢 Sucesso'), ('info', '🔵 Informação'), ('alerta', '🟡 Alerta')], default='info', max_length=10, verbose_name='Tipo')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
