# Generated by Django 6.0.6 on 2026-06-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ficha_cadastral',
            field=models.FileField(blank=True, null=True, upload_to='fichas_cadastrais/'),
        ),
    ]
