# Generated by Django 6.0.6 on 2026-06-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_cliente_ficha_cadastral'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrato_proposta',
            field=models.FileField(blank=True, null=True, upload_to='propostas_contratos/'),
        ),
    ]
