# Generated by Django 6.0.6 on 2026-06-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_cliente_contrato_proposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrato_proposta',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='contrato_proposta',
            field=models.FileField(blank=True, null=True, upload_to='propostas_contratos/'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='comercial.cliente'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='estagio',
            field=models.CharField(choices=[('Prospecção', 'Prospecção'), ('Qualificação', 'Qualificação'), ('Proposta', 'Proposta Enviada'), ('Negociação', 'Negociação'), ('Fechado_Ganhou', '🏆 Fechado (Ganhou)'), ('Fechado_Perdeu', '❌ Fechado (Perdeu)')], db_index=True, default='Prospecção', max_length=20),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
