# Generated by Django 6.0.6 on 2026-06-18 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_remove_cliente_contrato_proposta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteOportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_projeto', models.CharField(help_text='Ex: TI / Projeto Expansão Fabril', max_length=150, verbose_name='Setor / Projeto ou Empresa Destinada')),
                ('data_envio', models.DateField(verbose_name='Data de Envio do Equipamento')),
                ('dias_duracao', models.PositiveIntegerField(default=7, verbose_name='Quantidade de Dias de Teste')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Técnicas / Escopo do Teste')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('oportunidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teste', to='comercial.oportunidade')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='comercial.testeoportunidade')),
            ],
        ),
    ]
