# Generated by Django 6.0.6 on 2026-06-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_testeoportunidade_equipamentoteste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='estagio',
            field=models.CharField(choices=[('Prospecção', 'Prospecção'), ('Qualificação', 'Qualificação'), ('Proposta', 'Proposta Enviada'), ('Negociação', 'Negociação'), ('Em_Teste', '🔬 Em Teste / Validação'), ('Fechado_Ganhou', '🏆 Fechado (Aprovado)'), ('Fechado_Perdeu', '❌ Fechado (Perdeu)')], db_index=True, default='Prospecção', max_length=20),
        ),
    ]
