# Generated by Django 6.0.6 on 2026-06-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_alter_oportunidade_estagio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidade',
            old_name='contrato_proposta',
            new_name='contracto_proposta',
        ),
    ]
