# Generated by Django 6.0.6 on 2026-06-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_rename_contrato_proposta_oportunidade_contracto_proposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor responsável pela carteira deste cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteira_clientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
