# Generated by Django 6.0.6 on 2026-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_cliente_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentoteste',
            name='numero_serie',
            field=models.CharField(max_length=100, verbose_name='Número de Série'),
        ),
    ]
