# Generated by Django 6.0.6 on 2026-06-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_alter_equipamentoteste_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contato_responsavel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contato Responsável'),
        ),
    ]
