# Generated by Django 6.0.6 on 2026-07-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_cliente_contato_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oportunidade',
            old_name='contracto_proposta',
            new_name='contrato_proposta',
        ),
    ]
